version: '3.8'

services:
  weather-service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./weather_data:/app/weather_data
      - ./weather_cache:/app/weather_cache
      - ./events.db:/app/events.db
